name: e_commerce_web_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  get: ^4.7.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^8.0.0
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.9
  pinput: ^5.0.0
  otp_autofill: ^4.0.0
  dropdown_textfield: ^1.0.8
  flutter_screenutil: ^5.9.3
  graphql_flutter: ^5.1.2
  json_serializable: ^6.9.0
  easy_localization: ^3.0.7
  dotted_border: ^2.1.0
  file_picker: ^8.1.7
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  flutter_vlc_player: ^7.4.3
  chewie: ^1.8.0
  iconsax: ^0.0.8
  rxdart: ^0.28.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.1
  fitted_gridview: ^1.0.1
  mime: ^2.0.0
  step_progress_indicator: ^1.0.2
  intl_phone_field: ^3.2.0
  fluttertoast: ^8.2.8
  im_stepper: ^1.0.1+1
  intl_utils: ^2.8.7
  bottom_picker: ^2.8.0
  loader_overlay: ^4.0.1
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  sign_in_with_apple: ^6.1.3
  google_sign_in_ios: ^5.7.8
  scroll_to_index: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  just_audio: ^0.9.42
  comment_tree: ^0.3.0
  preload_page_view: ^0.2.0
  connectivity_plus: ^6.1.2
  package_info_plus: ^8.1.2
  any_link_preview: ^3.0.2
  flutter_link_previewer: ^3.2.2
  path: ^1.9.1
  permission_handler: ^11.3.1
  record: ^5.2.0
  get_thumbnail_video: ^0.7.3
  smooth_page_indicator: ^1.2.0+3
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  video_compress: ^3.1.4
  photo_view: ^0.15.0
  photo_manager: ^3.6.4
  share_plus: ^10.1.4
  loading_animation_widget: ^1.3.0
  skeletonizer: ^1.4.3
  flutter_launcher_icons: ^0.14.3
  flutter_mentions: ^2.0.1
  hydrated_bloc: ^10.0.0
  uuid: ^4.5.1
  flutter_animate: ^4.5.2

  time: ^2.1.5
  open_filex: ^4.7.0
  encrypt: ^5.0.3
  flutter_keyboard_visibility: ^6.0.0
  swipe_to: ^1.0.6
  just_waveform: ^0.0.7
  sqflite: ^2.4.2
  hive: ^2.2.3
  internet_connection_checker_plus: ^2.7.2
  extended_nested_scroll_view: ^6.2.1
  unicode: ^1.1.8
  flutter_rating: ^2.0.2
  google_fonts: ^6.2.1


# flutter_launcher_icons:
#   image_path_android: "lib/assets/images/ic_launcher.png"
#   image_path_ios: "lib/assets/images/ic_launcher.png"
#   android: true
#   ios: true
#   adaptive_icon_background: "lib/assets/images/ic_launcher.png"
#   adaptive_icon_foreground: "lib/assets/images/ic_launcher.png"
#   adaptive_icon_foreground_inset: 16
#   adaptive_icon_monochrome: "lib/assets/images/ic_launcher.png"
#   min_sdk_android: 21
#   remove_alpha_ios: true
#   background_color_ios: "#ffffff"
#   web:
#     generate: true
#     image_path: "lib/assets/images/ic_launcher.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "lib/assets/images/ic_launcher.png"
#     icon_size: 48
#   macos:
#     generate: true
#     image_path: "lib/assets/images/ic_launcher.png"




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4

  flutter_gen_runner: ^5.7.0
  flutter_gen: ^5.7.0
  intl_translation: ^0.20.0
  flutter_lints: ^5.0.0
dependency_overrides:
  video_player_android: 2.7.1

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter_native_splash:
  background_image: lib/assets/images/background_splash.png
  image: lib/assets/images/Logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: lib/assets/images/Logo.png
    icon_background_color: "0xffEF3E2C"
    image_dark: lib/assets/images/Logo.png
    icon_background_color_dark: "#0xffEF3E2C"
  web: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/fonts/
  
  fonts:
    - family: Integral CF
      fonts:
        - asset: lib/assets/fonts/Fontspring-DEMO-integralcf-regular.otf
        - asset: lib/assets/fonts/Fontspring-DEMO-integralcf-medium.otf
        - asset: lib/assets/fonts/Fontspring-DEMO-integralcf-bold.otf


# flutter_intl:
#   enabled: true