// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCujEd5ngS0te6akHQDv1rzCbQ75GQRHtc',
    appId: '1:54345482703:web:57e1fea2b0344c608652ba',
    messagingSenderId: '54345482703',
    projectId: 'admin-panal-ecommerce',
    authDomain: 'admin-panal-ecommerce.firebaseapp.com',
    storageBucket: 'admin-panal-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHAD-auJom9EQQzMiKAJYdinzN6vBrFnQ',
    appId: '1:54345482703:android:dee5566fded2be198652ba',
    messagingSenderId: '54345482703',
    projectId: 'admin-panal-ecommerce',
    storageBucket: 'admin-panal-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEClEnRq58MPlFd81lwQSdYWNLajnncug',
    appId: '1:54345482703:ios:74b0a09bc1cc36c28652ba',
    messagingSenderId: '54345482703',
    projectId: 'admin-panal-ecommerce',
    storageBucket: 'admin-panal-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEClEnRq58MPlFd81lwQSdYWNLajnncug',
    appId: '1:54345482703:ios:74b0a09bc1cc36c28652ba',
    messagingSenderId: '54345482703',
    projectId: 'admin-panal-ecommerce',
    storageBucket: 'admin-panal-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCujEd5ngS0te6akHQDv1rzCbQ75GQRHtc',
    appId: '1:54345482703:web:619eb7a72940b2958652ba',
    messagingSenderId: '54345482703',
    projectId: 'admin-panal-ecommerce',
    authDomain: 'admin-panal-ecommerce.firebaseapp.com',
    storageBucket: 'admin-panal-ecommerce.firebasestorage.app',
  );
}
